### ISSUE TITLE
Create utills for adding noise to image 

### ISSUE THREAD

**Issue by Albly** [Albly/Sparce_image_reconstruction#2]
Implement a function that adds AWGN to the image with denoted SNR (Signal to Noise ratio).
It can be added to file `utills.py`.

**Comment by Skrikunov** [comment]
Are you going to add complex or real Gaussian noise? I suppose that we are to use real noise.

**Comment by Albly** [comment]
Real one. As images are real, then we have to use real AWGN to distort them, and only after transformations into the frequency domain we will get Complex values.

**Comment by Albly** [comment]
@Skrikunov I've added a function for noise generation using SNR. Check it, please. Also, I saw that a lot of papers uses not SNR terms for image noising, but PSNR (Peak single to noise ratio), which uses peak amplitude, not mean power. Seems reasonable in terms of images... What do you think? 
```
def fromDb(value):
    '''Transforms Decibels to ratio'''
    return 10**(value/10.0)


def get_noise(signal, SNR_dB):
    '''
    Generates Additive white Gaussian noise (AWGN) with the same shape
    as shape of input @signal. Power of noise is calculsted by given
    @SNR_db signal to noise ratio [dB].  
    '''

    P_signal = torch.mean(torch.abs(signal)**2) # calculate power of the signal [W]
    D_noise = P_signal/fromDb(SNR_dB)           # calculate power of noise [W]
    
    mu = torch.zeros(1)                         # Mean of AWGN 
    sigma = torch.sqrt(D_noise/2)               # Deviation of AWGN

    shape = signal.shape
    noise = torch.normal(mean = mu.repeat(shape), std = sigma.repeat(shape)) # Noise vector
    return noise 
```

**Comment by Albly** [comment]
Approved. [Final version](https://github.com/Albly/Sparce_image_reconstruction/blob/master/utils.py)
