### ISSUE TITLE
Prepare datasets and functions for image processing.

### ISSUE THREAD

**Issue by Albly** [Albly/Sparce_image_reconstruction#3]
We are going to use grayscale images. The preferable size is 512x512 (to understand how reconstruction works with detailed images). But speeding up, smaller images can be used. 
I've found these datasets, which can be used at least for validation: 
1) USC SIPI :  https://sipi.usc.edu/database/database.php?volume=misc&image=38#top
2) TAMPARE17  : https://webpages.tuni.fi/imaging/tampere17/
Implement code for downloading the datasets and preprocessing them (torch Dataset and Dataloader)

**Comment by Skrikunov** [comment]
It's more convenient to use Kaggle link to download USC-SIPI because here all database is in a single archive https://www.kaggle.com/luffyluffyluffy/the-uscsipi-image-database
